---
driver:
#  name: vagrant
  name: docker

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
#  - name: ubuntu-14.04
  - name: centos-6.7
    driver_config:
      socket: tcp://192.168.99.100:2376
      provision_command: curl -L https://www.opscode.com/chef/install.sh | bash
      require_chef_omnibus: false
      use_sudo: false

suites:
  - name: default
    run_list:
      - recipe[jenkins-ato::default]
    attributes:
