name 'jenkins-ato'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures jenkins-ato'
long_description 'Installs/Configures jenkins-ato'
version '0.1.0'

depends 'yum'
depends 'apt'
depends 'java'
